const GOOGLE_ORIGIN='https://www.google.com';
const MARVEL_SMART_LINK='https://marvel.smart.link/fiir7ec77';
const MARVEL_LEGACY_SHARE='https://share.marvel.com/sharing/legacy/';
const META_TTL=60*60*24*30;

function unescapeHtml(value=''){return String(value).replace(/\\u002F/gi,'/').replace(/\\u003A/gi,':').replace(/\\\//g,'/').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&#58;/g,':')}
function exactGoogleQuery(title,issue,year){return `site:marvel.com/comics/issue/ "${title}" "${issue?`#${issue}`:''}" ${year} Marvel Unlimited`}
function luckyUrl(title,issue,year){return `${GOOGLE_ORIGIN}/search?btnI=1&q=${encodeURIComponent(exactGoogleQuery(title,issue,year))}`}
function normalGoogleUrl(title,issue,year){return `${GOOGLE_ORIGIN}/search?q=${encodeURIComponent(exactGoogleQuery(title,issue,year))}`}
function isMarvelIssueUrl(value=''){try{const u=new URL(value,GOOGLE_ORIGIN);return /(^|\.)marvel\.com$/i.test(u.hostname)&&/^\/comics\/issue\/\d+\//i.test(u.pathname)}catch{return false}}
function cleanMarvelIssueUrl(value=''){try{const u=new URL(value,GOOGLE_ORIGIN);return `${u.protocol}//${u.host}${u.pathname}`}catch{return ''}}
function sourceIdFromIssueUrl(issueUrl=''){try{return new URL(issueUrl).pathname.match(/^\/comics\/issue\/(\d+)/i)?.[1]||''}catch{return ''}}
function unwrapGoogleLocation(location=''){try{const a=new URL(location,GOOGLE_ORIGIN);if(isMarvelIssueUrl(a.href))return cleanMarvelIssueUrl(a.href);if(/google\./i.test(a.hostname)&&a.pathname==='/url'){const target=a.searchParams.get('q')||a.searchParams.get('url')||'';if(isMarvelIssueUrl(target))return cleanMarvelIssueUrl(target)}}catch{}return ''}
function extractMarvelIssueFromGoogleHtml(html=''){const clean=unescapeHtml(html).replace(/%2F/gi,'/').replace(/%3A/gi,':');const direct=clean.match(/https?:\/\/(?:www\.)?marvel\.com\/comics\/issue\/\d+\/[A-Za-z0-9_()%.,+\-]+/gi)||[];for(const c of direct)if(isMarvelIssueUrl(c))return cleanMarvelIssueUrl(c);const links=clean.match(/\/url\?[^"'<>\s]+/gi)||[];for(const link of links){try{const p=new URL(link.replace(/&amp;/g,'&'),GOOGLE_ORIGIN),target=p.searchParams.get('q')||p.searchParams.get('url')||'';if(isMarvelIssueUrl(target))return cleanMarvelIssueUrl(target)}catch{}}return ''}
async function fetchGoogle(url,redirect='manual'){return fetch(url,{redirect,headers:{'User-Agent':'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1','Accept':'text/html,application/xhtml+xml','Accept-Language':'es-ES,es;q=0.9,en;q=0.6'}})}
async function resolveExactIssueWithGoogle(title,issue,year){const lucky=luckyUrl(title,issue,year);try{const response=await fetchGoogle(lucky,'manual'),loc=unwrapGoogleLocation(response.headers.get('Location')||'');if(loc)return loc;if(isMarvelIssueUrl(response.url))return cleanMarvelIssueUrl(response.url);const html=await response.text(),from=extractMarvelIssueFromGoogleHtml(html);if(from)return from}catch(e){console.error('Google lucky resolver:',e)}try{const response=await fetchGoogle(normalGoogleUrl(title,issue,year),'follow'),html=await response.text(),from=extractMarvelIssueFromGoogleHtml(html);if(from)return from}catch(e){console.error('Google normal resolver:',e)}return ''}
async function fetchHtml(url){const response=await fetch(url,{redirect:'follow',headers:{'User-Agent':'Mozilla/5.0 (compatible; MarvelLectura/2.1)','Accept':'text/html,application/xhtml+xml','Accept-Language':'en-US,en;q=0.9'}});if(!response.ok)throw new Error(`${url} respondió ${response.status}`);return response.text()}
function extractReaderData(html,issueUrl){const clean=unescapeHtml(html),match=clean.match(/https:\/\/read\.marvel\.com\/#\/book\/(\d+)/i);return{readerId:match?.[1]||'',webUrl:match?.[0]||issueUrl}}
function absoluteImage(url=''){let v=unescapeHtml(url).trim();if(v.startsWith('//'))v='https:'+v;return /^https?:\/\//i.test(v)?v:''}
function extractCoverUrl(html=''){const clean=unescapeHtml(html);let patterns=[/<meta[^>]+property=["']og:image["'][^>]+content=["']([^"']+)["']/i,/<meta[^>]+content=["']([^"']+)["'][^>]+property=["']og:image["']/i,/"image"\s*:\s*"(https?:[^"\\]+(?:\\.[^"\\]*)*)"/i,/"image_url"\s*:\s*"([^"]+)"/i];for(const p of patterns){const m=clean.match(p);if(m){const u=absoluteImage(m[1]);if(u)return u}}return ''}
async function resolveLegacyDrn(readerId){if(!readerId)return '';const html=await fetchHtml(`${MARVEL_LEGACY_SHARE}${encodeURIComponent(readerId)}`),clean=unescapeHtml(html).replace(/%3A/gi,':');let explicit=clean.match(/(?:[?&]|\b)drn=([^&"'<>\s]+)/i)?.[1]||'';if(explicit){try{explicit=decodeURIComponent(explicit)}catch{}return explicit}return clean.match(/drn:src:marvel:unison::prod:[0-9a-f-]{36}/i)?.[0]||''}
function buildSmartLink(drn,sourceId){if(!drn||!sourceId)return '';const u=new URL(MARVEL_SMART_LINK);u.searchParams.set('type','issue');u.searchParams.set('drn',drn);u.searchParams.set('sourceId',sourceId);return u.toString()}
function cacheKey(title,issue,year){const u=new URL('https://marvel-meta-cache.invalid/item');u.searchParams.set('title',title);u.searchParams.set('issue',issue);u.searchParams.set('year',year);return new Request(u.toString())}
async function resolveMeta(title,issue,year){
  const key=cacheKey(title,issue,year),cache=typeof caches!=='undefined'?caches.default:null;
  if(cache){const hit=await cache.match(key);if(hit){try{return await hit.json()}catch{}}}
  const issueUrl=await resolveExactIssueWithGoogle(title,issue,year);
  if(!issueUrl){const data={available:false,issueUrl:'',sourceId:'',readerId:'',drn:'',smartLink:'',webUrl:luckyUrl(title,issue,year),coverUrl:'',reason:'issue-not-found'};return data}
  const sourceId=sourceIdFromIssueUrl(issueUrl),html=await fetchHtml(issueUrl),{readerId,webUrl}=extractReaderData(html,issueUrl),coverUrl=extractCoverUrl(html);
  let drn='',smartLink='';
  if(readerId&&sourceId){try{drn=await resolveLegacyDrn(readerId);smartLink=buildSmartLink(drn,sourceId)}catch(e){console.error('Legacy DRN:',e)}}
  const data={available:Boolean(smartLink),issueUrl,sourceId,readerId,drn,smartLink,webUrl,coverUrl,reason:smartLink?'ok':readerId?'drn-unavailable':'reader-unavailable'};
  if(cache){const response=Response.json(data,{headers:{'Cache-Control':`public, max-age=${META_TTL}`}});await cache.put(key,response.clone()).catch(()=>{})}
  return data
}
function redirect(location){return new Response(null,{status:302,headers:{Location:location,'Cache-Control':'private, no-store'}})}
function errorPage(fallback,msg='No he podido construir el enlace móvil de Marvel Unlimited.'){const safe=String(fallback).replace(/&/g,'&amp;').replace(/"/g,'&quot;'),text=String(msg).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));return new Response(`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Marvel Unlimited</title><style>body{margin:0;min-height:100dvh;display:grid;place-items:center;background:#f3f1ec;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#17181c}.box{width:min(88vw,430px);text-align:center}.logo{display:inline-block;background:#e62429;color:#fff;padding:5px 8px;font-weight:900;font-size:22px}a{display:block;margin-top:20px;padding:14px;border-radius:14px;background:#fff;color:#333;border:1px solid #ddd8cf;text-decoration:none;font-weight:800}p{color:#74747b;font-size:13px;line-height:1.5}</style></head><body><div class="box"><span class="logo">MARVEL</span><h2>Número localizado</h2><p>${text}</p><a href="${safe}">Abrir este número en la web</a></div></body></html>`,{status:502,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'}})}

export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname!=='/api/marvel/open')return env.ASSETS.fetch(request);const title=(url.searchParams.get('title')||'').trim(),issue=(url.searchParams.get('issue')||'').trim(),year=(url.searchParams.get('year')||'').trim(),mode=(url.searchParams.get('mode')||'web').toLowerCase();if(!title)return new Response('Falta el título del cómic.',{status:400});const lucky=luckyUrl(title,issue,year);if(mode==='web')return redirect(lucky);try{const meta=await resolveMeta(title,issue,year);if(mode==='meta')return Response.json(meta,{headers:{'Cache-Control':`public, max-age=${META_TTL}`}});if(mode==='debug')return Response.json({title,issue,year,...meta},{headers:{'Cache-Control':'no-store'}});if((mode==='ios'||mode==='android')&&meta.smartLink)return redirect(meta.smartLink);return errorPage(meta.webUrl||lucky,meta.reason==='reader-unavailable'?'Marvel Unlimited no ofrece este número en su lector digital.':'Marvel no ha devuelto el identificador móvil de este número.')}catch(e){console.error('Marvel resolver:',e);if(mode==='meta')return Response.json({available:false,webUrl:lucky,reason:'resolver-error'},{status:200,headers:{'Cache-Control':'public, max-age=3600'}});return errorPage(lucky,'Se ha producido un error al construir el enlace de Marvel Unlimited.')}}};
